---
title: "linelistBayes: an introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Why is this package necessary

Essentially, the reporting delay distribution is unknown because the time-dependent infectivity ( R(t) ) is unknown.

Say you have 100 people who at t0 start showing symptoms.

So, this is a two-step process

So linelistBayes


```{r setup}
library(linelistBayes)
```

You have count data
```{r example1}
data("sample_dates")
data("sample_location")
data("sample_cases")

head(sample_dates)
head(sample_cases)
```

create your `caseCounts` object
```{r casecounts}
caseCounts <- create_caseCounts(date_vec = sample_dates,
                                location_vec = sample_location,
                                cases_vec = sample_cases)

# get the first wave only
caseCounts <- caseCounts[1:80, ]
head(caseCounts)
```

Serial Interval: 
```{r serial}
sip <- si(14, 4.29, 1.18)
```

Back-calculate:
```{r backcalc}
out_list <- run_backnow(caseCounts, 
                        MAX_ITER = as.integer(2000), 
                        norm_sigma = 0.2,
                        sip = sip,
                        NB_maxdelay = as.integer(20),
                        NB_size = as.integer(6),
                        printProgress = 1,
                        reportF_missP = 0.6)
```

And plot
```{r plot1}
# plot
plot(out_list, "est")

plot(out_list, "rt")
```


